language: node_js
node_js: 9

before_script:
  - yarn
  - yarn lint
  - yarn unit

script:
  - yarn build
  - zip -r mon-arbitre-raquette dist

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: mon-arbitre-raquette.zip
  skip_cleanup: true
  on:
    tags: true
